### ISSUE TITLE
No bibliography

### ISSUE THREAD

**Issue by gcapes** [tombishop1/thesis-latex-manc#6]
Perhaps we should have at least one citation in the template, so that the bibliography shows by default? I can't get the biblatex citations to work - can you have a look?

**Comment by tombishop1** [comment]
The template has a few different inline citations to the two references in the file textandxref.tex - see line 12:
`This document uses a package that deals with inline citations and automatically generates a bibliography. It is powerful in the way it can format the inline references; for example, it can cite a reference in parentheses \Parencite[\textit{e.g.}][]{Payne2011}, or without. It can cite just the authors names, \citeauthor{Porinchu2003}, or include a figure reference \Parencite[\textit{e.g.}][Figure 1]{Payne2011}. `

**Comment by gcapes** [comment]
My mistake - I'm just struggling with the biblatex citations so don't have a bibliography (any more). Cheers
